CREATE TABLE IF NOT EXISTS account (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    balance DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    id UUID NOT NULL,
    ts TIMESTAMP,
    amount DOUBLE PRECISION NOT NULL
);